### ISSUE TITLE
Add support for NBD_FLAG_CAN_MULTI_CONN to the server

### ISSUE THREAD

**Issue by pPanda-beta** [pojntfx/go-nbd#4]
At this point the current `nbd-server` supports only 1 connection per client. For sequential reads kernel wont be able to create multiple connections and read in parallel. 

It would be best if we support this at least for readonly servers, for the sake of performance. 

### Doubt: World is moving into a single socket based model and multiplexing, e.g. HTTP2, why can't we follow that?

Because NBD protocol do not have any alternative multiplexing mechanism. Some underlying storage layers only perform well when consumed in parallel. e.g. GCS, S3 or any blobstorage. For a large sequential IO, best performance can only be achieved if we start reading in parallel.

**Comment by pojntfx** [comment]
That would be very interesting! From an implementation perspective, I def. see this as being possible, and its a minimal enough extension for it to keep being close to the baseline implementation while offering performance improvements IMHO. Currently, we just read messages from a single connection, switch on their option, forward them to the backend and stop when the client sends the disconnect, so switching to this could probably be done by finding a way to track a client and then just spawning this loop for each new connection I suppose.

**Comment by pPanda-beta** [comment]
I tried experimenting by just making one line change [here](https://github.com/pojntfx/go-nbd/blob/b8f5045f34d669752a8f2dc431f5cd0bab498685/pkg/server/nbd.go#L144) and it worked.

```diff
- 					TransmissionFlags: 0,
+ 					TransmissionFlags: 0b1000_0001_0000_0000,
```

First high bit  represents [NBD_FLAG_HAS_FLAGS](https://github.com/torvalds/linux/blob/f7757129e3dea336c407551c98f50057c22bb266/include/uapi/linux/nbd.h#L50)
and 8th one represents [NBD_FLAG_CAN_MULTI_CONN](https://github.com/torvalds/linux/blob/f7757129e3dea336c407551c98f50057c22bb266/include/uapi/linux/nbd.h#L56)

We can define those constants and make the flag part of `Options struct`.

**Comment by pojntfx** [comment]
That's neat, I'll def. take a look. Having parallelism could def. speed things up - and the backends already need to handle locking themselves since its possible to connect more than one client, so this should be possible in a backwards-compatible way, too.

**Comment by pojntfx** [comment]
So - I got it to work on the server-side (its just setting a flag as you mentioned, basically), but I can't get it to work on the client-side; if I call `NBD_SET_SOCK` more times than 1, I just get `invalid argument` when I call `NBD_DO_IT`. Any ideas what might be going on here @pPanda-beta? 

Hack/branch for `go-ndb` that starts implementing this: https://github.com/pojntfx/go-nbd/commit/eb21896f22d088def33040c05618d0308eb095e9
Hack/branch for `r3map` that starts implementing this: https://github.com/pojntfx/r3map/commit/2529c4ae9156eaf7a86c82989fcb138f859ed8b4

If we can get this to work, we'll probably be able to get very significant performance increases in related repos like [r3map](https://github.com/pojntfx/r3map), which is nice of course. Here is how the C version implements it: https://github.com/NetworkBlockDevice/nbd/blob/master/nbd-client.c#L1206-L1239

I basically copied it (if the whitespace diff is hidden in `go-nbd`'s client its just +4 lines), it should be a simple enough change in theory.

**Comment by pojntfx** [comment]
Released in https://github.com/pojntfx/go-nbd/releases/tag/v0.3.0
