### ISSUE TITLE
Size return 0 with standard blockDevices in FileBackend which leads to mount error on client side

### ISSUE THREAD

**Issue by efrasyab** [pojntfx/go-nbd#8]
if Size() function of the FileBackend would be revised as below, standard block devices could be mounted successfully from client side.

func (b *FileBackend) Size() (int64, error) {
	stat, err := b.file.Seek(0,2)
	if err != nil {
		return -1, err
	}
	return stat, nil
}

**Comment by pojntfx** [comment]
Thank you! Implemented in 2d78be2564f3835178508cb61c0a84d562f80364
